### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by kristiantomov** [TechzoneMC/SpawnShield#13]
Here's the log - 

[14:52:39 ERROR]: Could not pass event PlayerMoveEvent to SpawnShield v1.1.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-PaperSpigot-7f032d5-e91aed8]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-PaperSpigot-7f032d5-e91aed8]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-PaperSpigot-7f032d5-e91aed8]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-PaperSpigot-7f032d5-e91aed8]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:271) [spigot-1.8.8.jar:git-PaperSpigot-7f032d5-e91aed8]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [spigot-1.8.8.jar:git-PaperSpigot-7f032d5-e91aed8]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot-1.8.8.jar:git-PaperSpigot-7f032d5-e91aed8]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-PaperSpigot-7f032d5-e91aed8]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot-1.8.8.jar:git-PaperSpigot-7f032d5-e91aed8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:770) [spigot-1.8.8.jar:git-PaperSpigot-7f032d5-e91aed8]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:371) [spigot-1.8.8.jar:git-PaperSpigot-7f032d5-e91aed8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:709) [spigot-1.8.8.jar:git-PaperSpigot-7f032d5-e91aed8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:612) [spigot-1.8.8.jar:git-PaperSpigot-7f032d5-e91aed8]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NullPointerException
        at com.trc202.CombatTag.CombatTag.getRemainingTagTime(CombatTag.java:129) ~[?:?]
        at com.trc202.CombatTag.CombatTag.isInCombat(CombatTag.java:160) ~[?:?]
        at com.trc202.CombatTagApi.CombatTagApi.isInCombat(CombatTagApi.java:26) ~[?:?]
        at net.techcable.spawnshield.combattag.legacy.CombatTagLegacySupport.isTagged(CombatTagLegacySupport.java:52) ~[?:?]
        at net.techcable.spawnshield.combattag.CombatTagHelper.isTagged(CombatTagHelper.java:55) ~[?:?]
        at net.techcable.spawnshield.forcefield.ForceFieldListener.onMove(ForceFieldListener.java:55) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-PaperSpigot-7f032d5-e91aed8]
        ... 15 more

**Comment by Techcable** [comment]
CombatTagLegacy is not supported. Use CombatTagPlus.

**Comment by kristiantomov** [comment]
im using CombatTag? but ok, ill use combattag+
