### ISSUE TITLE
Errorspam in console.

### ISSUE THREAD

**Issue by Aireesan** [TechzoneMC/SpawnShield#4]
Hello, here is my plugin list:
Plugins (22): AsyncWorldEditInjector, WorldEdit, AsyncWorldEdit, BiomeControl, ConsoleSay, Essentials, EssentialsChat, GroupManager, HardcoreDeathBan, ScheduledAnnouncer2, Vault, EssentialsSpawn, WorldGuard, TitleManager, Factions, CombatTagPlus, ChestCommands, PvPTimer, AsyncWorldEdit-TitleManager, ServerSigns, NexGen_KoTHs, SilkSpawners
- SpawnShield (removed so I can get the output in console)

I am using the latest version of WG, WE, SpawnShield and CombatTagPlus.

```
[01:23:46 WARN]: [SpawnShield] Task #143 for SpawnShield v1.1.0 generated an exception
java.lang.RuntimeException: java.lang.NullPointerException
        at net.techcable.spawnshield.libs.techutils.Reflection.callMethod(Reflection.java:85) ~[?:?]
        at net.techcable.spawnshield.CombatAPI.getRemainingTagTime(CombatAPI.java:99) ~[?:?]
        at net.techcable.spawnshield.CombatAPI.isTagged(CombatAPI.java:63) ~[?:?]
        at net.techcable.spawnshield.tasks.TeleportSafezoningTask.run(TeleportSafezoningTask.java:46) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft_server.jar:git-Spigot-6a6b839-b0e81a4]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [minecraft_server.jar:git-Spigot-6a6b839-b0e81a4]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:726) [minecraft_server.jar:git-Spigot-6a6b839-b0e81a4]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [minecraft_server.jar:git-Spigot-6a6b839-b0e81a4]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [minecraft_server.jar:git-Spigot-6a6b839-b0e81a4]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [minecraft_server.jar:git-Spigot-6a6b839-b0e81a4]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
        at sun.reflect.GeneratedMethodAccessor161.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
        at net.techcable.spawnshield.libs.techutils.Reflection.callMethod(Reflection.java:81) ~[?:?]
        ... 10 more
```

**Comment by Aireesan** [comment]
It's worth adding it only spams when I am inside spawn.

**Comment by Techcable** [comment]
Update to build 16.
